name: push-img

on:
  workflow_dispatch:
    inputs:
      BASE_IMG_VER:
        description:
          "Specify the version of the base alpine image. The `docker-svn` 's version tag inherits this code."
        required: true
        type: number

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ inputs.BASE_IMG_VER }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/docker-svn:${{ inputs.BASE_IMG_VER }}
            ${{ secrets.DOCKERHUB_USERNAME }}/docker-svn:latest
          build-args: BASE_IMG_VER=${{ inputs.BASE_IMG_VER }}
          labels: |
            org.opencontainers.image.authors="Omae Tadashi <56265995+0xTadash1@users.noreply.github.com>"
            org.opencontainers.image.url="https://github.com/0xTadash1/docker-svn"
            org.opencontainers.image.documentation="https://github.com/0xTadash1/docker-svn/blob/main/README.md"
            org.opencontainers.image.source="https://github.com/0xTadash1/docker-svn/blob/main/Dockerfile"
            org.opencontainers.image.version="${{ inputs.BASE_IMG_VER }}"


